/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthResguardosIndexRouteImport } from './routes/_auth/resguardos/index'
import { Route as AuthDocumentosIndexRouteImport } from './routes/_auth/documentos/index'
import { Route as AuthDictamenesIndexRouteImport } from './routes/_auth/dictamenes/index'
import { Route as AuthArticulosIndexRouteImport } from './routes/_auth/articulos/index'
import { Route as AuthResguardosCrearRouteImport } from './routes/_auth/resguardos/crear'
import { Route as AuthDictamenesCreateRouteImport } from './routes/_auth/dictamenes/create'
import { Route as AuthResguardosUuidInspeccionarRouteImport } from './routes/_auth/resguardos/$uuid/inspeccionar'
import { Route as AuthDictamenesUuidEditarRouteImport } from './routes/_auth/dictamenes/$uuid/editar'
import { Route as AuthDictamenesUuidActionRouteImport } from './routes/_auth/dictamenes/$uuid/$action'
import { Route as AuthArticulosUuidActualizarRouteImport } from './routes/_auth/articulos/$uuid/actualizar'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthResguardosIndexRoute = AuthResguardosIndexRouteImport.update({
  id: '/resguardos/',
  path: '/resguardos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocumentosIndexRoute = AuthDocumentosIndexRouteImport.update({
  id: '/documentos/',
  path: '/documentos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDictamenesIndexRoute = AuthDictamenesIndexRouteImport.update({
  id: '/dictamenes/',
  path: '/dictamenes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArticulosIndexRoute = AuthArticulosIndexRouteImport.update({
  id: '/articulos/',
  path: '/articulos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResguardosCrearRoute = AuthResguardosCrearRouteImport.update({
  id: '/resguardos/crear',
  path: '/resguardos/crear',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDictamenesCreateRoute = AuthDictamenesCreateRouteImport.update({
  id: '/dictamenes/create',
  path: '/dictamenes/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResguardosUuidInspeccionarRoute =
  AuthResguardosUuidInspeccionarRouteImport.update({
    id: '/resguardos/$uuid/inspeccionar',
    path: '/resguardos/$uuid/inspeccionar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDictamenesUuidEditarRoute =
  AuthDictamenesUuidEditarRouteImport.update({
    id: '/dictamenes/$uuid/editar',
    path: '/dictamenes/$uuid/editar',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDictamenesUuidActionRoute =
  AuthDictamenesUuidActionRouteImport.update({
    id: '/dictamenes/$uuid/$action',
    path: '/dictamenes/$uuid/$action',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthArticulosUuidActualizarRoute =
  AuthArticulosUuidActualizarRouteImport.update({
    id: '/articulos/$uuid/actualizar',
    path: '/articulos/$uuid/actualizar',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/dictamenes/create': typeof AuthDictamenesCreateRoute
  '/resguardos/crear': typeof AuthResguardosCrearRoute
  '/articulos/': typeof AuthArticulosIndexRoute
  '/dictamenes/': typeof AuthDictamenesIndexRoute
  '/documentos/': typeof AuthDocumentosIndexRoute
  '/resguardos/': typeof AuthResguardosIndexRoute
  '/articulos/$uuid/actualizar': typeof AuthArticulosUuidActualizarRoute
  '/dictamenes/$uuid/$action': typeof AuthDictamenesUuidActionRoute
  '/dictamenes/$uuid/editar': typeof AuthDictamenesUuidEditarRoute
  '/resguardos/$uuid/inspeccionar': typeof AuthResguardosUuidInspeccionarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/dictamenes/create': typeof AuthDictamenesCreateRoute
  '/resguardos/crear': typeof AuthResguardosCrearRoute
  '/articulos': typeof AuthArticulosIndexRoute
  '/dictamenes': typeof AuthDictamenesIndexRoute
  '/documentos': typeof AuthDocumentosIndexRoute
  '/resguardos': typeof AuthResguardosIndexRoute
  '/articulos/$uuid/actualizar': typeof AuthArticulosUuidActualizarRoute
  '/dictamenes/$uuid/$action': typeof AuthDictamenesUuidActionRoute
  '/dictamenes/$uuid/editar': typeof AuthDictamenesUuidEditarRoute
  '/resguardos/$uuid/inspeccionar': typeof AuthResguardosUuidInspeccionarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_auth/dictamenes/create': typeof AuthDictamenesCreateRoute
  '/_auth/resguardos/crear': typeof AuthResguardosCrearRoute
  '/_auth/articulos/': typeof AuthArticulosIndexRoute
  '/_auth/dictamenes/': typeof AuthDictamenesIndexRoute
  '/_auth/documentos/': typeof AuthDocumentosIndexRoute
  '/_auth/resguardos/': typeof AuthResguardosIndexRoute
  '/_auth/articulos/$uuid/actualizar': typeof AuthArticulosUuidActualizarRoute
  '/_auth/dictamenes/$uuid/$action': typeof AuthDictamenesUuidActionRoute
  '/_auth/dictamenes/$uuid/editar': typeof AuthDictamenesUuidEditarRoute
  '/_auth/resguardos/$uuid/inspeccionar': typeof AuthResguardosUuidInspeccionarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dictamenes/create'
    | '/resguardos/crear'
    | '/articulos/'
    | '/dictamenes/'
    | '/documentos/'
    | '/resguardos/'
    | '/articulos/$uuid/actualizar'
    | '/dictamenes/$uuid/$action'
    | '/dictamenes/$uuid/editar'
    | '/resguardos/$uuid/inspeccionar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dictamenes/create'
    | '/resguardos/crear'
    | '/articulos'
    | '/dictamenes'
    | '/documentos'
    | '/resguardos'
    | '/articulos/$uuid/actualizar'
    | '/dictamenes/$uuid/$action'
    | '/dictamenes/$uuid/editar'
    | '/resguardos/$uuid/inspeccionar'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_guest/login'
    | '/_auth/dictamenes/create'
    | '/_auth/resguardos/crear'
    | '/_auth/articulos/'
    | '/_auth/dictamenes/'
    | '/_auth/documentos/'
    | '/_auth/resguardos/'
    | '/_auth/articulos/$uuid/actualizar'
    | '/_auth/dictamenes/$uuid/$action'
    | '/_auth/dictamenes/$uuid/editar'
    | '/_auth/resguardos/$uuid/inspeccionar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/resguardos/': {
      id: '/_auth/resguardos/'
      path: '/resguardos'
      fullPath: '/resguardos/'
      preLoaderRoute: typeof AuthResguardosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/documentos/': {
      id: '/_auth/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof AuthDocumentosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictamenes/': {
      id: '/_auth/dictamenes/'
      path: '/dictamenes'
      fullPath: '/dictamenes/'
      preLoaderRoute: typeof AuthDictamenesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/articulos/': {
      id: '/_auth/articulos/'
      path: '/articulos'
      fullPath: '/articulos/'
      preLoaderRoute: typeof AuthArticulosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/resguardos/crear': {
      id: '/_auth/resguardos/crear'
      path: '/resguardos/crear'
      fullPath: '/resguardos/crear'
      preLoaderRoute: typeof AuthResguardosCrearRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictamenes/create': {
      id: '/_auth/dictamenes/create'
      path: '/dictamenes/create'
      fullPath: '/dictamenes/create'
      preLoaderRoute: typeof AuthDictamenesCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/resguardos/$uuid/inspeccionar': {
      id: '/_auth/resguardos/$uuid/inspeccionar'
      path: '/resguardos/$uuid/inspeccionar'
      fullPath: '/resguardos/$uuid/inspeccionar'
      preLoaderRoute: typeof AuthResguardosUuidInspeccionarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictamenes/$uuid/editar': {
      id: '/_auth/dictamenes/$uuid/editar'
      path: '/dictamenes/$uuid/editar'
      fullPath: '/dictamenes/$uuid/editar'
      preLoaderRoute: typeof AuthDictamenesUuidEditarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictamenes/$uuid/$action': {
      id: '/_auth/dictamenes/$uuid/$action'
      path: '/dictamenes/$uuid/$action'
      fullPath: '/dictamenes/$uuid/$action'
      preLoaderRoute: typeof AuthDictamenesUuidActionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/articulos/$uuid/actualizar': {
      id: '/_auth/articulos/$uuid/actualizar'
      path: '/articulos/$uuid/actualizar'
      fullPath: '/articulos/$uuid/actualizar'
      preLoaderRoute: typeof AuthArticulosUuidActualizarRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDictamenesCreateRoute: typeof AuthDictamenesCreateRoute
  AuthResguardosCrearRoute: typeof AuthResguardosCrearRoute
  AuthArticulosIndexRoute: typeof AuthArticulosIndexRoute
  AuthDictamenesIndexRoute: typeof AuthDictamenesIndexRoute
  AuthDocumentosIndexRoute: typeof AuthDocumentosIndexRoute
  AuthResguardosIndexRoute: typeof AuthResguardosIndexRoute
  AuthArticulosUuidActualizarRoute: typeof AuthArticulosUuidActualizarRoute
  AuthDictamenesUuidActionRoute: typeof AuthDictamenesUuidActionRoute
  AuthDictamenesUuidEditarRoute: typeof AuthDictamenesUuidEditarRoute
  AuthResguardosUuidInspeccionarRoute: typeof AuthResguardosUuidInspeccionarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDictamenesCreateRoute: AuthDictamenesCreateRoute,
  AuthResguardosCrearRoute: AuthResguardosCrearRoute,
  AuthArticulosIndexRoute: AuthArticulosIndexRoute,
  AuthDictamenesIndexRoute: AuthDictamenesIndexRoute,
  AuthDocumentosIndexRoute: AuthDocumentosIndexRoute,
  AuthResguardosIndexRoute: AuthResguardosIndexRoute,
  AuthArticulosUuidActualizarRoute: AuthArticulosUuidActualizarRoute,
  AuthDictamenesUuidActionRoute: AuthDictamenesUuidActionRoute,
  AuthDictamenesUuidEditarRoute: AuthDictamenesUuidEditarRoute,
  AuthResguardosUuidInspeccionarRoute: AuthResguardosUuidInspeccionarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
