/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthInventarioIndexRouteImport } from './routes/_auth/inventario/index'
import { Route as AuthDictamenIndexRouteImport } from './routes/_auth/dictamen/index'
import { Route as AuthDictamenCreateRouteImport } from './routes/_auth/dictamen/create'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthInventarioIndexRoute = AuthInventarioIndexRouteImport.update({
  id: '/inventario/',
  path: '/inventario/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDictamenIndexRoute = AuthDictamenIndexRouteImport.update({
  id: '/dictamen/',
  path: '/dictamen/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDictamenCreateRoute = AuthDictamenCreateRouteImport.update({
  id: '/dictamen/create',
  path: '/dictamen/create',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/dictamen/create': typeof AuthDictamenCreateRoute
  '/dictamen/': typeof AuthDictamenIndexRoute
  '/inventario/': typeof AuthInventarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/dictamen/create': typeof AuthDictamenCreateRoute
  '/dictamen': typeof AuthDictamenIndexRoute
  '/inventario': typeof AuthInventarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_auth/dictamen/create': typeof AuthDictamenCreateRoute
  '/_auth/dictamen/': typeof AuthDictamenIndexRoute
  '/_auth/inventario/': typeof AuthInventarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dictamen/create' | '/dictamen/' | '/inventario/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dictamen/create' | '/dictamen' | '/inventario'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_guest/login'
    | '/_auth/dictamen/create'
    | '/_auth/dictamen/'
    | '/_auth/inventario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/inventario/': {
      id: '/_auth/inventario/'
      path: '/inventario'
      fullPath: '/inventario/'
      preLoaderRoute: typeof AuthInventarioIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictamen/': {
      id: '/_auth/dictamen/'
      path: '/dictamen'
      fullPath: '/dictamen/'
      preLoaderRoute: typeof AuthDictamenIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictamen/create': {
      id: '/_auth/dictamen/create'
      path: '/dictamen/create'
      fullPath: '/dictamen/create'
      preLoaderRoute: typeof AuthDictamenCreateRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDictamenCreateRoute: typeof AuthDictamenCreateRoute
  AuthDictamenIndexRoute: typeof AuthDictamenIndexRoute
  AuthInventarioIndexRoute: typeof AuthInventarioIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDictamenCreateRoute: AuthDictamenCreateRoute,
  AuthDictamenIndexRoute: AuthDictamenIndexRoute,
  AuthInventarioIndexRoute: AuthInventarioIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
