/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthInventarioIndexRouteImport } from './routes/_auth/inventario/index'
import { Route as AuthDocumentosIndexRouteImport } from './routes/_auth/documentos/index'
import { Route as AuthDictamenesIndexRouteImport } from './routes/_auth/dictamenes/index'
import { Route as AuthInventarioCreateRouteImport } from './routes/_auth/inventario/create'
import { Route as AuthDictamenesCreateRouteImport } from './routes/_auth/dictamenes/create'
import { Route as AuthDictamenesUuidActionRouteImport } from './routes/_auth/dictamenes/$uuid/$action'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthInventarioIndexRoute = AuthInventarioIndexRouteImport.update({
  id: '/inventario/',
  path: '/inventario/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocumentosIndexRoute = AuthDocumentosIndexRouteImport.update({
  id: '/documentos/',
  path: '/documentos/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDictamenesIndexRoute = AuthDictamenesIndexRouteImport.update({
  id: '/dictamenes/',
  path: '/dictamenes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventarioCreateRoute = AuthInventarioCreateRouteImport.update({
  id: '/inventario/create',
  path: '/inventario/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDictamenesCreateRoute = AuthDictamenesCreateRouteImport.update({
  id: '/dictamenes/create',
  path: '/dictamenes/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDictamenesUuidActionRoute =
  AuthDictamenesUuidActionRouteImport.update({
    id: '/dictamenes/$uuid/$action',
    path: '/dictamenes/$uuid/$action',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/dictamenes/create': typeof AuthDictamenesCreateRoute
  '/inventario/create': typeof AuthInventarioCreateRoute
  '/dictamenes/': typeof AuthDictamenesIndexRoute
  '/documentos/': typeof AuthDocumentosIndexRoute
  '/inventario/': typeof AuthInventarioIndexRoute
  '/dictamenes/$uuid/$action': typeof AuthDictamenesUuidActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/dictamenes/create': typeof AuthDictamenesCreateRoute
  '/inventario/create': typeof AuthInventarioCreateRoute
  '/dictamenes': typeof AuthDictamenesIndexRoute
  '/documentos': typeof AuthDocumentosIndexRoute
  '/inventario': typeof AuthInventarioIndexRoute
  '/dictamenes/$uuid/$action': typeof AuthDictamenesUuidActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_auth/dictamenes/create': typeof AuthDictamenesCreateRoute
  '/_auth/inventario/create': typeof AuthInventarioCreateRoute
  '/_auth/dictamenes/': typeof AuthDictamenesIndexRoute
  '/_auth/documentos/': typeof AuthDocumentosIndexRoute
  '/_auth/inventario/': typeof AuthInventarioIndexRoute
  '/_auth/dictamenes/$uuid/$action': typeof AuthDictamenesUuidActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dictamenes/create'
    | '/inventario/create'
    | '/dictamenes/'
    | '/documentos/'
    | '/inventario/'
    | '/dictamenes/$uuid/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dictamenes/create'
    | '/inventario/create'
    | '/dictamenes'
    | '/documentos'
    | '/inventario'
    | '/dictamenes/$uuid/$action'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_guest/login'
    | '/_auth/dictamenes/create'
    | '/_auth/inventario/create'
    | '/_auth/dictamenes/'
    | '/_auth/documentos/'
    | '/_auth/inventario/'
    | '/_auth/dictamenes/$uuid/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/inventario/': {
      id: '/_auth/inventario/'
      path: '/inventario'
      fullPath: '/inventario/'
      preLoaderRoute: typeof AuthInventarioIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/documentos/': {
      id: '/_auth/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof AuthDocumentosIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictamenes/': {
      id: '/_auth/dictamenes/'
      path: '/dictamenes'
      fullPath: '/dictamenes/'
      preLoaderRoute: typeof AuthDictamenesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventario/create': {
      id: '/_auth/inventario/create'
      path: '/inventario/create'
      fullPath: '/inventario/create'
      preLoaderRoute: typeof AuthInventarioCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictamenes/create': {
      id: '/_auth/dictamenes/create'
      path: '/dictamenes/create'
      fullPath: '/dictamenes/create'
      preLoaderRoute: typeof AuthDictamenesCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dictamenes/$uuid/$action': {
      id: '/_auth/dictamenes/$uuid/$action'
      path: '/dictamenes/$uuid/$action'
      fullPath: '/dictamenes/$uuid/$action'
      preLoaderRoute: typeof AuthDictamenesUuidActionRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDictamenesCreateRoute: typeof AuthDictamenesCreateRoute
  AuthInventarioCreateRoute: typeof AuthInventarioCreateRoute
  AuthDictamenesIndexRoute: typeof AuthDictamenesIndexRoute
  AuthDocumentosIndexRoute: typeof AuthDocumentosIndexRoute
  AuthInventarioIndexRoute: typeof AuthInventarioIndexRoute
  AuthDictamenesUuidActionRoute: typeof AuthDictamenesUuidActionRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDictamenesCreateRoute: AuthDictamenesCreateRoute,
  AuthInventarioCreateRoute: AuthInventarioCreateRoute,
  AuthDictamenesIndexRoute: AuthDictamenesIndexRoute,
  AuthDocumentosIndexRoute: AuthDocumentosIndexRoute,
  AuthInventarioIndexRoute: AuthInventarioIndexRoute,
  AuthDictamenesUuidActionRoute: AuthDictamenesUuidActionRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
